services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: csn
      POSTGRES_PASSWORD: csn_pass
      POSTGRES_DB: csn_payment
    ports:
      - "5443:5432"
    volumes:
      - payment_pgdata:/var/lib/postgresql/data

volumes:
  payment_pgdata:
