services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: csn
      POSTGRES_PASSWORD: csn_pass
      POSTGRES_DB: csn_chat
    ports:
      - "5439:5432"
    volumes:
      - chat_pgdata:/var/lib/postgresql/data

volumes:
  chat_pgdata:
