services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: csn
      POSTGRES_PASSWORD: csn_pass
      POSTGRES_DB: csn_lyrics
    ports:
      - "5435:5432"
    volumes:
      - lyrics_pgdata:/var/lib/postgresql/data

volumes:
  lyrics_pgdata:
